### ISSUE TITLE
(detail given) Unable to paste in Windows 10, Davinci Resolve 

### ISSUE THREAD

**Issue by Howitbee** [VilleOlof/DavinciClipboardScript#3]
Hi, firstly thanks so much for making and providing this script,

I have installed the script according to your instructions, but when I execute it, nothing happens. In the console, the following message is given: [ ...i Resolve\Support\Fusion\Scripts\Edit\ImageClipboard.lua:4: invalid escape sequence near '"D:' ]
![image](https://github.com/VilleOlof/DavinciClipboardScript/assets/115403108/ab473125-4e8f-416b-87b6-0f3ccfb0429a)

I have already ensured the slash is the correct way in the chosen file directory (see screencap below) and assigned a keyboard shortcut. Additionally, the clipboard older does show on my UI, but no image pastes into it at all. (2nd image just below)
![image](https://github.com/VilleOlof/DavinciClipboardScript/assets/115403108/9394f60b-31b2-4cad-be5b-5032491d86ed)
![image](https://github.com/VilleOlof/DavinciClipboardScript/assets/115403108/b6649e53-fc2f-45f2-83cd-ba790f98c8ff)

Other things I have tried:
- Using another drive for the save folder (doesn't work even when using the same drive that resolve is installed to. It just gives the same error but replaces location of 'invalid escape sequence')
- Opening/ Closing Resolve
- Re-executing the script
- Changed the keyboard shortcut multiple times (idk I was desperate)
- Resetting Davinci System Settings in the Preferences Window

This could really make my editing life sooo much easier if I can get it to work. Please lend me your help! 🥺🙏🏾

**Comment by VilleOlof** [comment]
Seems like you have `\` (back slashes) in your path, but the last one is correct. All must be forward slashes ( `/` ). The `\` around editing should be switched to `/`. Since it gives the error directly after the "D:" part

**Comment by Howitbee** [comment]
Omg I understand now!
And glad to say it works :^D 
I was not expecting a response so quick. God and the universe and everything good bless you, thank you so much 💌
